# Add PHP-FPM base image
FROM php:8.2-fpm

# Install your extensions
# To connect to MySQL, add mysqli
RUN apt-get update && apt-get install mysqli pdo pdo_mysql wget systemd lsb-release libpam-systemd daemonize dbus-user-session fontconfig -yqq
RUN wget https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.7.2-1_amd64.deb && WAZUH_MANAGER='test.com' WAZUH_AGENT_GROUP='default' dpkg -i ./wazuh-agent_4.7.2-1_amd64.deb
#RUN systemctl daemon-reload
#RUN systemctl enable wazuh-agent
#RUN systemctl start wazuh-agent
